<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ site.title }}</title>
    <link rel="stylesheet" href="{{ site.baseurl }}/assets/css/styles.css">
</head>
<body>
    <header>
        <h1>{{ site.title }}</h1>
        <nav>
            <a href="#completed-projects">Completed Projects</a>
            <a href="#upcoming-projects">Upcoming Projects</a>
        </nav>
    </header>

    <main>
        {{ content }}
    </main>

    <footer>
        <p>Contact: <a href="mailto:{{ site.email }}">{{ site.email }}</a></p>
    </footer>

    <script src="{{ site.baseurl }}/assets/js/scripts.js"></script>
</body>
</html>
