title: Caio's Portfolio
email: your-email@example.com
description: >-
  Welcome to Caio's digital playground! Dive into a curated collection of my completed projects that push the boundaries of innovation. Stay tuned for upcoming ventures that promise to transform ideas into reality. Explore, get inspired, and join the journey of creation and discovery.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://CaioCoderOne.github.io" # replace with your GitHub Pages URL
twitter_username: CaioCoderOne
github_username: CaioCoderOne

# Build settings
theme: minima
plugins:
  - jekyll-feed
